/* This file is auto generated, do not edit! */
/* Generated by Moshe Gottlieb ON  Thursday November 02 2017*/


#pragma once

#include <awscsdk/include/aws.h>
#include <awscsdk/include/s3.h>
#include <awscsdk/include/ses.h>
#include <awscsdk/include/sqs.h>
